"""Tail pool generator (spec P2.2-P2.6). Stdlib only. Deterministic.

Writes data/tail/filings.json, tasks.jsonl, drift_tasks.jsonl, manifest.json.

Company/split/slice assignment comes from tailguard/companies.py; prompt
templates for S0/T1/T2/T3/T6/D1 are PROMPT_TEMPLATES imported (not copied)
from data/generate_tasks.py. Base-value formulas copy make_filing's formulas
(same draws, same order) with an independent Random(SEED) stream.

Decisions where the spec leaves filing parts unspecified (logged):
- filing["slice"] tags the TEXT family: standard-text filings (shared by
  S0/T4/T5 tasks) are tagged "S0"; task records carry the task slice.
- notes section: standard wording for every slice.
- mda: the spec's explicit text where given (STD, T1, T2); standard wording
  with money() of current values for T3/T6; billions phrasing for D1.
- D1 tables hold the rounded ground-truth millions (gt), consistent with gt.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))

from data.generate_tasks import PROMPT_TEMPLATES  # noqa: E402
from tailguard.companies import COMPANIES, GROUPS, SPLIT_POS  # noqa: E402
from tailguard.config import (DELTA, EPSILONS, N_DRIFT, N_TASKS, SEED,  # noqa: E402
                              SLICE_SHARE, SLICES, SPLITS, TAIL_DIR)
from tailguard.logging_utils import write_config  # noqa: E402

YEARS = [2022, 2023, 2024]
M = ["revenue", "net_income", "total_assets", "operating_cash_flow"]
LABEL = {"revenue": "Revenue", "net_income": "Net income",
         "total_assets": "Total assets",
         "operating_cash_flow": "Operating cash flow"}
VERB = {"revenue": "was", "net_income": "was", "total_assets": "were",
        "operating_cash_flow": "was"}

T4_SYN = {"revenue": ["sales", "net sales", "top line", "turnover"],
          "net_income": ["profit", "net earnings", "bottom line", "earnings"],
          "total_assets": ["asset base", "total assets on the balance sheet",
                           "balance sheet size"],
          "operating_cash_flow": ["cash from operations", "CFO",
                                  "operating cash generation",
                                  "cash generated by operating activities"]}
T4_TEMPLATES = [
    "What was {company}'s {syn} for FY{year}? Cite the filing.",
    "Find {company} {year} {syn} — give value + evidence.",
    "{ticker} FY{year} {syn} — lookup and cite.",
]
T5_SHORT = {"revenue": "rev", "net_income": "NI", "total_assets": "TA",
            "operating_cash_flow": "OCF"}
T5_TEMPLATES = [
    "{ticker_lower} {short} fy{yy}?",
    "{company_typo} {year} {short}",
    "{short} {ticker} {year} pls cite",
]

NOTES_STD = "Notes to financial statements FY{year}. See statements for audited figures."


def money(v: int) -> str:
    return f"${v:,} million"


def typo(company: str) -> str:
    first, _, rest = company.partition(" ")
    if len(first) < 4:
        return company
    chars = list(first)
    chars[2], chars[3] = chars[3], chars[2]
    return "".join(chars) + (" " + rest if rest else "")


def group_of(idx: int) -> str:
    for g, r in GROUPS.items():
        if idx in r:
            return g
    raise ValueError(f"company index {idx} in no group")


def split_of(group: str, pos: int) -> str:
    table = SPLIT_POS["STD"] if group == "STD" else SPLIT_POS["TX"]
    for s, r in table.items():
        if pos in r:
            return s
    raise ValueError(f"pos {pos} in group {group} in no split")


def base_values() -> dict:
    """filing_id -> {company, ticker, year, values}. Draws mirror make_filing."""
    rng = random.Random(SEED)
    out = {}
    for company, ticker in COMPANIES:
        for year in YEARS:
            base = rng.randint(8_000, 60_000)
            values = {
                "revenue": base,
                "net_income": int(base * rng.uniform(0.05, 0.22)),
                "total_assets": int(base * rng.uniform(1.5, 3.5)),
                "operating_cash_flow": int(base * rng.uniform(0.1, 0.35)),
            }
            out[f"{ticker}-10K-{year}"] = {"company": company, "ticker": ticker,
                                           "year": year, "values": values}
    return out


def std_tables(v: dict) -> dict:
    return {"income_statement": {"revenue": v["revenue"],
                                "net_income": v["net_income"]},
            "balance_sheet": {"total_assets": v["total_assets"]},
            "cash_flow": {"operating_cash_flow": v["operating_cash_flow"]}}


def build_filings(base: dict) -> dict:
    """filing_id -> full filing record with slice text."""
    rng_prior = random.Random(SEED + 2)
    rng_prior_first = random.Random(SEED + 3)
    rng_adj = random.Random(SEED + 4)
    rng_dist_first = random.Random(SEED + 5)
    filings = {}
    for idx, (company, ticker) in enumerate(COMPANIES):
        group = group_of(idx)
        for year in YEARS:
            fid = f"{ticker}-10K-{year}"
            v = base[fid]["values"]
            r, n, a, o = v["revenue"], v["net_income"], v["total_assets"], v["operating_cash_flow"]
            if group == "STD":
                fam = "S0"
                statements = (
                    f"Consolidated Statements of Operations, FY{year}. "
                    f"Revenue was {money(r)}. Net income was {money(n)}. "
                    f"Total assets were {money(a)}. "
                    f"Operating cash flow was {money(o)}.")
                mda = (f"Management Discussion FY{year} for {company}. "
                       f"Revenue of {money(r)} reflects operating performance.")
                tables = std_tables(v)
            elif group == "T1":
                fam = "T1"
                statements = (
                    f"Consolidated Statements of Operations, FY{year}. "
                    f"(In thousands of U.S. dollars.) Revenue was ${r * 1000:,}. "
                    f"Net income was ${n * 1000:,}. Total assets were ${a * 1000:,}. "
                    f"Operating cash flow was ${o * 1000:,}.")
                mda = (f"Management Discussion FY{year} for {company}. "
                       f"Revenue of ${r * 1000:,} thousand reflects operating performance.")
                tables = {k: {m: val * 1000 for m, val in t.items()}
                          for k, t in std_tables(v).items()}
            elif group == "T2":
                fam = "T2"
                prior_first = rng_prior_first.choice([True, False])
                sents = []
                for m in M:
                    cur = v[m]
                    if year > 2022:
                        prev = base[f"{ticker}-10K-{year - 1}"]["values"][m]
                    else:
                        prev = int(cur * rng_prior.uniform(0.85, 0.97))
                        while prev == cur:
                            prev = int(cur * rng_prior.uniform(0.85, 0.97))
                    if prior_first:
                        sents.append(f"{LABEL[m]} {VERB[m]} {money(prev)} in FY{year - 1} "
                                     f"and {money(cur)} in FY{year}.")
                    else:
                        sents.append(f"{LABEL[m]} {VERB[m]} {money(cur)} in FY{year} "
                                     f"and {money(prev)} in FY{year - 1}.")
                statements = "Consolidated Statements of Operations. " + " ".join(sents)
                mda = (f"Management Discussion FY{year} for {company}. "
                       f"Revenue of {money(r)} in FY{year} reflects operating performance.")
                tables = std_tables(v)
            elif group == "T3":
                fam = "T3"
                dist_first = rng_dist_first.choice([True, False])
                sents = []
                for m in M:
                    adj = int(v[m] * rng_adj.uniform(1.03, 1.12))
                    while adj == v[m]:
                        adj = int(v[m] * rng_adj.uniform(1.03, 1.12))
                    gaap = f"{LABEL[m]} {VERB[m]} {money(v[m])}."
                    dist = (f"Adjusted {LABEL[m].lower()}, a non-GAAP measure, "
                            f"{VERB[m]} {money(adj)}.")
                    sents.append(dist + " " + gaap if dist_first else gaap + " " + dist)
                statements = (f"Consolidated Statements of Operations, FY{year}. "
                              + " ".join(sents))
                mda = (f"Management Discussion FY{year} for {company}. "
                       f"Revenue of {money(r)} reflects operating performance.")
                tables = std_tables(v)
            elif group == "T6":
                fam = "T6"
                statements = (
                    f"Consolidated Financial Data, FY{year} (USD millions)\n"
                    f"Line item | FY{year}\n"
                    f"Revenue | {r:,}\nNet income | {n:,}\n"
                    f"Total assets | {a:,}\nOperating cash flow | {o:,}")
                mda = (f"Management Discussion FY{year} for {company}. "
                       f"Revenue of {money(r)} reflects operating performance.")
                tables = std_tables(v)
            elif group == "D1":
                fam = "D1"
                g = {m: round(v[m] / 100) * 100 for m in M}
                statements = (
                    f"Consolidated Statements of Operations, FY{year}. "
                    f"Revenue was ${g['revenue'] / 1000:.1f} billion. "
                    f"Net income was ${g['net_income'] / 1000:.1f} billion. "
                    f"Total assets were ${g['total_assets'] / 1000:.1f} billion. "
                    f"Operating cash flow was ${g['operating_cash_flow'] / 1000:.1f} billion.")
                mda = (f"Management Discussion FY{year} for {company}. "
                       f"Revenue of ${g['revenue'] / 1000:.1f} billion "
                       f"reflects operating performance.")
                tables = {"income_statement": {"revenue": g["revenue"],
                                               "net_income": g["net_income"]},
                          "balance_sheet": {"total_assets": g["total_assets"]},
                          "cash_flow": {"operating_cash_flow": g["operating_cash_flow"]}}
            else:  # pragma: no cover
                raise ValueError(group)
            notes = NOTES_STD.format(year=year)
            filings[fid] = {
                "filing_id": fid, "company": company, "ticker": ticker,
                "year": year, "form": "10-K",
                "source": "synthetic tail-slice filing (seeded, no real issuer)",
                "slice": fam, "values": v, "tables": tables,
                "sections": {"financial_statements": statements,
                             "mda": mda, "notes": notes},
            }
    return filings


def slice_companies(slc: str, split: str) -> list[int]:
    """Company indices serving (slice, split). S0/T4/T5 share STD companies."""
    group = "STD" if slc in ("S0", "T4", "T5") else slc
    gr = GROUPS[group]
    table = SPLIT_POS["STD"] if group == "STD" else SPLIT_POS["TX"]
    return [i for i in gr if (i - gr.start) in table[split]]


def ground_truth(filing: dict, metric: str, slc: str) -> dict:
    if slc == "T1":
        value = filing["values"][metric]
        return {"value": value, "value_str": money(value),
                "filing_id": filing["filing_id"],
                "section": "financial_statements",
                "evidence_substr": f"${value * 1000:,}"}
    if slc == "D1":
        gt = round(filing["values"][metric] / 100) * 100
        return {"value": gt, "value_str": money(gt),
                "filing_id": filing["filing_id"],
                "section": "financial_statements",
                "evidence_substr": f"${gt / 1000:.1f} billion"}
    if slc == "T6":
        value = filing["values"][metric]
        return {"value": value, "value_str": money(value),
                "filing_id": filing["filing_id"],
                "section": "financial_statements",
                "evidence_substr": f"{LABEL[metric]} | {value:,}"}
    value = filing["values"][metric]
    return {"value": value, "value_str": money(value),
            "filing_id": filing["filing_id"],
            "section": "financial_statements",
            "evidence_substr": money(value)}


def make_prompt(slc: str, filing: dict, metric: str, rng: random.Random) -> str:
    company, ticker, year = filing["company"], filing["ticker"], filing["year"]
    if slc == "T4":
        syn = rng.choice(T4_SYN[metric])
        t = rng.choice(T4_TEMPLATES)
        return t.format(company=company, syn=syn, year=year, ticker=ticker)
    if slc == "T5":
        short = T5_SHORT[metric]
        t = rng.choice(T5_TEMPLATES)
        return t.format(ticker_lower=ticker.lower(), short=short,
                        yy=str(year)[2:], company_typo=typo(company),
                        year=year, ticker=ticker)
    t = rng.choice(PROMPT_TEMPLATES)
    return t.format(company=company, metric=metric.replace("_", " "),
                    year=year, ticker=ticker)


def split_counts(split: str) -> dict:
    total = N_TASKS[split]
    counts = {s: round(total * SLICE_SHARE[s]) for s in SLICES}
    counts["S0"] += total - sum(counts.values())  # remainder to S0
    return counts


def build_tasks(filings: dict) -> tuple[list[dict], list[dict]]:
    by_id = filings
    tasks: list[dict] = []
    per_split_n = {s: 0 for s in SPLITS}
    for si, split in enumerate(SPLITS):
        for ci, slc in enumerate(SLICES):
            n = split_counts(split)[slc]
            rng = random.Random(SEED + 100 + si * 10 + ci)
            cands = [f for i in slice_companies(slc, split) for f in
                     [by_id[f"{COMPANIES[i][1]}-10K-{y}"] for y in YEARS]]
            for k in range(n):
                filing = rng.choice(cands)
                metric = rng.choice(M)
                prompt = make_prompt(slc, filing, metric, rng)
                tasks.append({
                    "task_id": f"tg-{split}-{per_split_n[split]:04d}",
                    "task_family": "financial_metric_extraction",
                    "prompt": prompt, "company": filing["company"],
                    "ticker": filing["ticker"], "year": filing["year"],
                    "metric": metric, "filing_id": filing["filing_id"],
                    "section": "financial_statements",
                    "slice": slc, "split": split,
                    "ground_truth": ground_truth(filing, metric, slc),
                })
                per_split_n[split] += 1
    drift: list[dict] = []
    rng = random.Random(SEED + 500)
    cands = [by_id[f"{COMPANIES[i][1]}-10K-{y}"]
             for i in GROUPS["D1"] for y in YEARS]
    for k in range(N_DRIFT):
        filing = rng.choice(cands)
        metric = rng.choice(M)
        prompt = make_prompt("D1", filing, metric, rng)
        drift.append({
            "task_id": f"tg-drift-{k:04d}",
            "task_family": "financial_metric_extraction",
            "prompt": prompt, "company": filing["company"],
            "ticker": filing["ticker"], "year": filing["year"],
            "metric": metric, "filing_id": filing["filing_id"],
            "section": "financial_statements",
            "slice": "D1", "split": "drift",
            "ground_truth": ground_truth(filing, metric, "D1"),
        })
    return tasks, drift


def sha256_file(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def generate(out_dir: Path | None = None, seed: int = SEED) -> dict:
    # seed is fixed by spec (SEED); the --seed flag exists per rule 11 and
    # main() rejects any other value.
    out = Path(out_dir) if out_dir else TAIL_DIR
    out.mkdir(parents=True, exist_ok=True)
    base = base_values()
    filings = build_filings(base)
    tasks, drift = build_tasks(filings)
    fp, tp, dp = out / "filings.json", out / "tasks.jsonl", out / "drift_tasks.jsonl"
    fp.write_text(json.dumps(filings, indent=1) + "\n")
    tp.write_text("\n".join(json.dumps(t) for t in tasks) + "\n")
    dp.write_text("\n".join(json.dumps(t) for t in drift) + "\n")
    counts = {s: {sl: sum(1 for t in tasks if t["split"] == s and t["slice"] == sl)
                  for sl in SLICES} for s in SPLITS}
    comp_map = {}
    for i, (c, t) in enumerate(COMPANIES):
        g = group_of(i)
        if g == "D1":
            comp_map[c] = {"ticker": t, "group": g, "split": "drift"}
        else:
            table = SPLIT_POS["STD"] if g == "STD" else SPLIT_POS["TX"]
            pos = i - GROUPS[g].start
            comp_map[c] = {"ticker": t, "group": g,
                           "split": split_of(g, pos), "pos_in_group": pos}
    manifest = {"seed": SEED, "counts": counts,
                "drift": {"slice": "D1", "n": len(drift)},
                "companies": comp_map,
                "sha256": {p.name: sha256_file(p) for p in (fp, tp, dp)}}
    (out / "manifest.json").write_text(json.dumps(manifest, indent=1) + "\n")
    return {"filings": len(filings), "tasks": len(tasks), "drift": len(drift),
            "manifest": manifest}


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=SEED)
    ap.add_argument("--out-dir", default=str(TAIL_DIR))
    a = ap.parse_args()
    if a.seed != SEED:
        raise SystemExit(f"spec fixes seed={SEED}; got {a.seed}")
    res = generate(Path(a.out_dir), a.seed)
    write_config(Path(a.out_dir) / "tasks.jsonl",
                 {"seed": a.seed, "out_dir": a.out_dir})
    print(json.dumps({k: v for k, v in res.items() if k != "manifest"}, indent=1))


if __name__ == "__main__":
    main()
